### ISSUE TITLE
install-sdk suspendend

### ISSUE THREAD

**Issue by Yannick1712** [MarcoG3/WhatsDump#18]
I tried to install sdk with: "python whatsdump.py --install-sdk" but after a few Seconds and some output lines it is suspendend: I got the following output, when I try to install sdk:

 _    _ _           _      ______
| |  | | |         | |     |  _  \
| |  | | |__   __ _| |_ ___| | | |_   _ _ __ ___  _ __
| |/\| | '_ \ / _` | __/ __| | | | | | | '_ ` _ \| '_ \
\  /\  / | | | (_| | |_\__ \ |/ /| |_| | | | | | | |_) |
 \/  \/|_| |_|\__,_|\__|___/___/  \__,_|_| |_| |_| .__/
                                                 | |
                                                 |_|
                        v0.2 beta

[INFO] SDK tools directory already exists, skipping download & extraction...
[INFO] Updating SDK from manager...
[=======================================] 100% Computing updates...
[INFO] Accepting SDK licenses..
All SDK package licenses accepted.======] 100% Computing updates...

Did you have any idea, if I am doing something wrong?

**Comment by yschoen** [comment]
I had the same issue. The error occurs at the step
s2 = self._run_cmd_sdkmanager("--list")
Adding show=True revealed that the script fails with:
  File "...\WhatsDump\src\android_sdk.py", line 67, in install
    if s2_out.find('extras;intel;Hardware_Accelerated_Execution_Manager') != -1:
AttributeError: 'NoneType' object has no attribute 'find'

I'm not sure where this find function should come from but it's not defined. The trouble was solved for me by deleting this line checking for 'extras;intel;Hardware_Accelerated_Execution_Manager' and taking
install_args += ' extras;intel;Hardware_Accelerated_Execution_Manager'
out of the if statement.

**Comment by MarcoG3** [comment]
Should be fixed in 4a04014

**Comment by Yannick1712** [comment]
Thanks for your answer. I tried your option, but it shows still the same and is suspendend.

The part of the code, which I channge:

 # Install required packages
        install_args = '--install emulator platform-tools platforms;android-23 system-images;android-23;google_apis;x86'
        install_args += ' extras;intel;Hardware_Accelerated_Execution_Manager'

        #if s2_out.find('extras;intel;Hardware_Accelerated_Execution_Manager') != -1:
         #   install_args += ' extras;intel;Hardware_Accelerated_Execution_Manager'

        logger.info('Installing packages from SDK Manager...')
        s3 = self._run_cmd_sdkmanager(install_args, input='y\n'*20, show=True)

        if s3.returncode != 0:
            logger.error('Could not install packages from SDK Manager')
            return False

I commented the two lines and copied the second line out of the if statement. Did I anything wrong?

**Comment by Yannick1712** [comment]
I don't know why but it's still not working. I have downloaded the new fixed android_sdk.py and tried again to install it, but it's still suspendend on the same spot...

Did you have any other idea?

**Comment by yschoen** [comment]
It might help if you add "show=True" to the arguments of sdkmanager commands and post the last output before it hangs.
For example: self._run_cmd_sdkmanager("--list") => self._run_cmd_sdkmanager("--list", show=True)
You can also use logger.info commands placed in the android_sdk script to find the last spot that is executed before it stops.

**Comment by Yannick1712** [comment]
Thank you for your help! I added the "show=True" and now all is working. Don't no why but it worked!
